---
- name: Install Nginx
  hosts: all
  #remote_user: debian
  #become: true
  serial: 5

  roles:
    - { role: loadbalancers, when: "'loadbalancers' in group_names" }
    - { role: backends, when: "'backends' in group_names" }
    #- { role: databases, when: "'databases' in group_names" }
    #- chrony
    #- nftables
    #- nginx

