---
- name: Debian OS
  block:

  - name: Install nftables
    ansible.builtin.apt:
      name: nftables
      state: present

  - name: Copy nftables.conf
    ansible.builtin.template:
      src: nftables.conf.j2
      dest: /etc/nftables.conf
      owner: root
      mode: 0600

  when: ansible_os_family == "Debian"

- name: RedHat OS
  block:

  - name: Install nftables
    ansible.builtin.dnf:
      name: nftables
      state: present

  - name: Copy nftables.conf
    ansible.builtin.template:
      src: nftables.conf.j2
      dest: /etc/sysconfig/nftables.conf
      owner: root
      mode: 0600

  when: ansible_os_family == "RedHat"

# systemctl restart nftables --now
- name: Restart NFTables
  ansible.builtin.service:
    name: nftables
    state: restarted
    enabled: yes
